travis:
  secure:
    BINSTAR_TOKEN: D3iZbOj3VPjW+SkL7SiXnbAB29VeWnwS9CuWWBMSJT3BD0ZOaug0mJqUjr72QTY5w5sumsMuUQjqYewnLsskWp6BNYgjvgq8iXonTNMwNVxjMOLP+GRCBrIgBb/VJfYPqPfe9EAdyldtfX0eSF+VGdr33anj9EOGI4VO71gjSwhMYwqVhP9pvajThGsPauYE1hdVIair35tqk1Qrht5yQ3lBfBPljj8SANPZmk4lbu3QUFUg5VkO2MaoPpfWP65N0rPB1S+4rA46lPIGfB9rCX7mioizothRDKvr5Clppxn/kNcsZpLnu5q0MVcDeallugblFdjkCIKHSfIBr8OOOOgmIjQSkEzA1wHRJvrm3huvfcSjHOBom3XJw6AqBbnAHPDIeVGUQmnU4MpfmgAQAdR5pmRxT+q7Zd2CkdPS8TxexWanwhfK4+QJ/nrYiYL4bzYOXRQmH8e1OvYq3AgrsRcKX/NkF2Eb2UvDhtbYbT2bWQw3z4DTO/U+0rEgiHf3NFDbQGMf57pEHge5nQFkTa41Y4nKrQBP4K4GM1v0yrgfMx3AdQdgjhw1CFfChVH0JuwVLATiMVidXUoJA73R8IdfNRCfJ5uo8oqST2JiQJk5WzM+u0cf2UhleWC04IIT0jmBsw5G9RNBk69vfJa9/rhYHPLrWW8I+KJ1p/AriLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
